apis/urls.py
from django.urls import path,include
from .views import ListPostViewSet
from rest_framework.routers import DefaultRouter

router=DefaultRouter()
router.register('project',ListPostViewSet,basename='project-apis')
urlpatterns = [
    
    
    path('',include(router.urls))

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from projects.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('projects.urls','projects'),namespace='projects')),
    path('apis/v/', include('apis.urls')),
    path('',include("square.urls")),
    path('',home,name='base')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
from .views import PostListView
urlpatterns = [
    
    path('', PostListView.as_view(), name='projects'),
    path('post/', views.createpost, name='create-post'),

    path('ajax/newsletter/', views.newsletter, name='newsletter')

]

square/urls.py
from django.urls import path
from . import views
from .views import PostListView
urlpatterns = [
    path('', PostListView.as_view(), name='projects'),

]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from pyuploadcare.dj.models import ImageField
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=155)
    url = models.URLField(max_length=255)
    description = models.TextField(max_length=255)
    technologies = models.CharField(max_length=200, blank=True)
    photo = ImageField(manual_crop='1380x900')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    date_posted = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f'{self.title}'

    @classmethod
    def search_project(cls, technologies):
        return cls.objects.filter(title__icontains=technologies).all()    

class Person(models.Model):
    name=models.CharField(max_length=200,null=True,blank=True)
    email=models.EmailField(max_length=200,null=True,blank=True)
    subject=models.CharField(max_length=200,null=True,blank=True)
    message=models.TextField(max_length=250,null=True,blank=True)

    def __str__(self):
        return f'{self.name}'

square/models.py
from django.db import models

# Create your models here.

projects/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        models=Person
        fields=('name','contact','subject','message')

apis/views.py
from django.shortcuts import render
from rest_framework import generics
from rest_framework import viewsets
from rest_framework import mixins
from .serializers import ProjectsSerializer
from projects import models
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication,BasicAuthentication
# Create your views here.
class ListPostViewSet(viewsets.GenericViewSet,mixins.ListModelMixin,mixins.UpdateModelMixin,mixins.CreateModelMixin,
                   mixins.RetrieveModelMixin,mixins.DestroyModelMixin ):
    serializer_class=ProjectsSerializer
    queryset=models.Post.objects.all()
    authentication_classes=[SessionAuthentication,BasicAuthentication]
    permission_classes=[IsAuthenticated]  

projects/views.py
from django.shortcuts import render
from django.http  import HttpResponse
import datetime as dt
from django.views.generic import ListView
from .models import Post,Person
from django.contrib import messages
from django.http import JsonResponse
from .email import send_welcome_email
# Create your views here.
class PostListView(ListView):
    model=Post
    template_name='projects/post_list.html'
    context_object_name = 'projects'
    ordering = ['-date_posted']

def createpost(request):
    if request.method == 'POST':
        if request.POST.get('name') and request.POST.get('subject') and request.POST.get('email') and request.POST.get('message'):
            post=Person()
            post.name= request.POST.get('name')
            post.subject= request.POST.get('subject')
            post.email= request.POST.get('email')
            post.message= request.POST.get('message')
      
            post.save()
            messages.success(request, f'{post.name} Your message has been successfully received and message sent to your email') 
            return render(request, 'base.html')  

    else:
        return render(request,'base.html')

def home(request):
    return render(request, 'base.html')

def newsletter(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    subject=request.POST.get('subject')
    message=request.POST.get('message')
    
    recipient=Person(name=name,email=email,subject=subject,message=message)
    recipient.save()
    send_welcome_email(name,email)
    data = {'success': 'Your message has been successfully received and message sent to your email'}
    return JsonResponse(data)

square/views.py
from django.shortcuts import render
from django.views.generic import ListView
from projects.models import Post
# Create your views here.
class PostListView(ListView):
    model=Post
    template_name='index.html'
    context_object_name = 'projects'
    ordering = ['-date_posted']

projects/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="index.html">B</a>
      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav nav ml-auto">
          <li class="nav-item"><a href="#home-section" class="nav-link"><span>Home</span></a></li>
          <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>
          <li class="nav-item"><a href="#skills-section" class="nav-link"><span>Skills</span></a></li>
          <li class="nav-item"><a href="project" class="nav-link"><span>Projects APIs</span></a></li>
          <li class="nav-item"><a href="#blog-section" class="nav-link"><span>My projects</span></a></li>
          <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>
        </ul>
      </div>
    </div>
  </nav>

projects/templates/projects/post_form.html
{%load static%}


<section class="ftco-section contact-section ftco-no-pb" data-section="contact">
        <div class="container">
          <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section text-center ftco-animate">
              <span class="subheading">Contact</span>
              <h2 class="mb-4">Contact Me</h2>
              <p></p>
            </div>
          </div>
          <div class="row no-gutters block-9">
            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="row no-gutters block-9">
          <div class="col-md-6 order-md-last d-flex">
              <form action="/post" class="bg-light p-5 contact-form" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control"id="name" name="name" placeholder="Your Name" required>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control"  id="email" name='email'placeholder="Your Email" required>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject"required>
                </div>
                <div class="form-group">
                  <textarea  name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Message" required></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" value="Send Message" class="btn btn-secondary py-3 px-5">
                </div>
              </form>
          
          </div>
      
          <div class="col-md-6 d-flex">
            <div class="img" style="background-image: url({%static 'images/3.jpg'%});"></div>
          </div>
          </div>
        </div>
  </section>    

projects/templates/projects/post_list.html
{%extends 'base.html'%}
{%load static%}
{%block content%}


  <section class="ftco-section ftco-project bg-light"  data-section="projects">
    <div class="container-fluid px-md-5">
      <div class="row justify-content-center pb-5">
        <div class="col-md-12 heading-section text-center ftco-animate">
          <span class="subheading">Accomplishments</span>
          <h2 class="mb-4">My Projects</h2>
          <p>These are some of my projects you can check<span><a href="https://github.com/barackmaund1">my github profile</a></span> </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 testimonial">
          <div class="carousel-project owl-carousel">
            {% for post in  projects %}
            <div class="item">
              <div class="project">
                <div class="img">
                  <img src="{{post.photo.cdn_url}}" class="img-fluid" alt="barack">
                  <a href="{{post.url}}"  class="icon image-popup d-flex justify-content-center align-items-center">
                    <span class="icon-expand"></span>
                  </a>
                </div>
                <div class="text px-4">
                  <h3><a href="{{post.url}}">{{post.title}}</a></h3>
                  <span>{{post.technologies}}</span>
                </div>
              </div>
            </div>
            {%endfor%}
         

          </div>
        </div>
      </div>
    </div>
  </section>
{%endblock%}

square/templates/index.html
{%load static%}
{% load bootstrap4%}

 
    
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

    <link rel="stylesheet" href="{%static 'css1/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css1/animate.css'%}">
    
    <link rel="stylesheet" href="{%static 'css1/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{%static 'css1/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{%static 'css1/magnific-popup.css'%}">

    <link rel="stylesheet" href="{%static 'css1/aos.css'%}">

    <link rel="stylesheet" href="{%static 'css1/ionicons.min.css'%}">
    
    <link rel="stylesheet" href="{%static 'css1/flaticon.css'%}">
    <link rel="stylesheet" href="{%static 'css1/icomoon.css'%}">
    <link rel="stylesheet" href="{%static 'css1/style.css'%}">
  

    


	
   
	<section class="testimony-section" data-section="testimony">
		<div class="container">
		  <div class="row ftco-animate justify-content-center">
			  <div class="col-md-12 d-flex align-items-center">
				  <div class="carousel-testimony owl-carousel">
					  <div class="item">
						  <div class="testimony-wrap d-flex align-items-stretch">
						<div class="user-img d-flex align-self-stretch" style="background-image: url({%static 'images1/rap.png'%})">
						</div>
						<div class="text d-flex align-items-center">
							<div>
								<div class="icon-quote">
									<span class="icon-quote-left"></span>
								</div>
							  <p class="mb-4">I love the way you solve problems.</p>
							  <p class="name">Raphael katana</p>
							  <span class="position">Technical mentor at Moringa school </span>
						  </div>
						</div>
					  </div>
					  </div>
					  <div class="item">
						  <div class="testimony-wrap d-flex align-items-stretch">
						<div class="user-img d-flex align-self-stretch" style="background-image: url({%static 'images1/emma.png'%})">
						</div>
						<div class="text d-flex align-items-center">
							<div>
								<div class="icon-quote">
									<span class="icon-quote-left"></span>
								</div>
							  <p class="mb-4">You are such a great leader! and responsible.</p>
							  <p class="name">Emma Sharon</p>
							  <span class="position">Technical mentor,Access department at moringa</span>
						  </div>
						</div>
					  </div>
					  </div>
				  </div>
			  </div>
		  </div>
		</div>
	  </section>
    
   
    
  

	
	  <section class="ftco-section contact-section ftco-no-pb" data-section="contact">
		<div class="container">
			<div class="row justify-content-center mb-5 pb-3">
			<div class="col-md-7 heading-section text-center ftco-animate">
			  <span class="subheading">Contact</span>
			  <h2 class="mb-4">Contact Me</h2>
			  <p></p>
			</div>
			{% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
		  </div>
		  <div class="row no-gutters block-9">
			<div class="col-md-6 order-md-last d-flex">
				<form action="{% url 'projects:newsletter' %}" class="bg-light p-5 contact-form" method="POST"  enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group">
					  <input type="text" class="form-control"id="name" name="name" placeholder="Your Name" required>
					</div>
					<div class="form-group">
					  <input type="text" class="form-control"  id="email" name='email'placeholder="Your Email" required>
					</div>
					<div class="form-group">
					  <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject"required>
					</div>
					<div class="form-group">
					  <textarea  name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Message" required></textarea>
					</div>
					<div class="form-group">
					  <input type="submit" value="Send Message" class="btn btn-secondary py-3 px-5">
					</div>
				</form>
			
			</div>
  
			<div class="col-md-6 d-flex">
				<div class="img" style="background-image: url({%static 'images/3.jpg'%});"></div>
			</div>
		  </div>
		</div>
	  </section>
  
	  <script src="{%static 'js1/jquery.min.js'%}"></script>
  <script src="{%static 'js1/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{%static 'js1/popper.min.js'%}"></script>
  <script src="{%static 'js1/bootstrap.min.js'%}"></script>
  <script src="{%static 'js1/jquery.easing.1.3.js'%}"></script>
  <script src="{%static 'js1/jquery.waypoints.min.js'%}"></script>
  <script src="{%static 'js1/jquery.stellar.min.js'%}"></script>
  <script src="{%static 'js1/owl.carousel.min.js'%}"></script>
  <script src="{%static 'js1/jquery.magnific-popup.min.js'%}"></script>
  <script src="{%static 'js1/aos.js'%}"></script>
  <script src="{%static 'js1/jquery.animateNumber.min.js'%}"></script>
  <script src="{%static 'js1/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{%static 'js1/google-map.js'%}"></script>
  <script src="{%static 'js1/main.js'%}"></script>
  <script type="text/javascript" src="{%static 'js1/newsletter.js'%}"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
 

square/templates/navbar1.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="index.html"><span>Barack.</span></a>
      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav nav ml-auto">
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="home"><span>Home</span></a></li>
        
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="about"><span>About</span></a></li>
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="projects"><span>Projects</span></a></li>
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="testimony"><span>Testimony</span></a></li>
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="contact"><span>Contact</span></a></li>
          <li class="nav-item"><a href="#" class="nav-link" data-nav-section="skills"><span>Skills</span></a></li>
        
        </ul>
      </div>
    </div>
  </nav>

square/templates/projects/form.html
{%load static%}